http:
  listen: ":8080"
  write_timeout: "15s"
  read_timeout: "15s"
  idle_timeout: "15s"

host: "http://localhost:8080"
queues:
  - name: "gpu u"
    gpus: [ "all" ]

  - name: "gpu dos"
    gpus: [ "all" ]