database: "postgres://skeduler:skeduler1234@database:5432/skeduler"

telegram:
  token: "5327559224:AAHXAV9Zd5NxmnMZWZIielNWqKKLYQrWabI"
  chat_id: 225012886

http:
  listen: ":8080"
  read_timeout: "15s"
  idle_timeout: "15s"

tokens:
  - "42"
  - "47"
  - "139"
